# Data

In [19]:
import numpy as np
import pandas as pd
from scipy.stats import entropy

a = np.random.random_integers(0, 9, (10, 10))
b = np.random.random_integers(0, 9, (10, 10))
c = np.random.random_integers(0, 9, (10, 10))

In [32]:
np.unique(a, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([17,  7,  8,  8, 11,  9,  7, 12, 15,  6]))

In [59]:
_ , countsA = np.unique(a, return_counts=True)
_ , countsB = np.unique(b, return_counts=True)
_ , countsC = np.unique(c, return_counts=True)
counts = np.array([countsA,countsB, countsC])
class_probs = np.array(pred_probability(counts))
class_probs

array([[1.7, 0.7, 0.8, 0.8, 1.1, 0.9, 0.7, 1.2, 1.5, 0.6],
       [1.1, 0.6, 1.7, 1.4, 0.9, 1. , 1.1, 0.2, 0.9, 1.1],
       [1. , 0.9, 1.2, 0.6, 0.9, 0.5, 1.2, 1.7, 0.9, 1.1]])

# Entropy

In [60]:
#Entropy using Scipy and Pandas
entropy(counts.T)

array([2.24496526, 2.21562301, 2.25189123])

Here entropy is very high more than 1
this shows very high disoder. Normal range of entropy is 0-1

In [62]:
#Entropy using Scipy and probability function

calss_probs = pred_probability(counts)
entropy(class_probs.T)

array([2.24496526, 2.21562301, 2.25189123])

In [22]:

def pred_probability(counts):
    prob = []
    for sample in counts:
        n_classes = len(sample)
        prob.append(sample/n_classes)
    return prob

# Classification Uncertainty

In [64]:
''' This approach selects the 1 most uncertain sample. Large number represents uncertainty. We should pass multiple lists of probs
instead of 1 sample to get a list of uncertainities and select the one with highest number. In this case pass axis = 1 for max function '''

1 - class_probs.max(axis = 1) 

array([-0.7, -0.7, -0.7])

# Margin Sampling

In [65]:
''' Considers the margin between first and second most likely prediction. It selects the sample with smallest margin, the smaller the margin between the prediction of two classes the more unsure the decision is. '''

part = np.partition(-class_probs, 1, axis=1)
margin = - part[:, 0] + part[:, 1]
margin

array([0.2, 0.3, 0.5])