# Data

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import entropy

a = np.random.random_integers(0, 9, (10, 10))
b = np.random.random_integers(0, 9, (10, 10))
c = np.random.random_integers(0, 9, (10, 10))

In [2]:
np.unique(a, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([11,  8, 12, 11, 15,  7, 12,  6,  9,  9]))

In [16]:

def pred_probability(counts):
    prob = []
    for sample in counts:
        n_classes = len(sample)
        prob.append(sample/n_classes)
    return prob

In [15]:
_ , countsA = np.unique(a, return_counts=True)
_ , countsB = np.unique(b, return_counts=True)
_ , countsC = np.unique(c, return_counts=True)
counts = np.array([countsA,countsB, countsC])
class_probs = np.array(pred_probability(counts))
class_probs

array([[1.1, 0.8, 1.2, 1.1, 1.5, 0.7, 1.2, 0.6, 0.9, 0.9],
       [0.8, 0.8, 1.1, 1.1, 0.7, 1.3, 1.1, 1.1, 0.7, 1.3],
       [0.6, 1.3, 1.2, 0.6, 1.2, 0.8, 1.2, 1. , 1.1, 1. ]])

# Entropy

In [ ]:
#Entropy using Scipy and Pandas
entropy(counts.T)

Here entropy is very high more than 1
this shows very high disoder. Normal range of entropy is 0-1

In [ ]:
#Entropy using Scipy and probability function

calss_probs = pred_probability(counts)
entropy(class_probs.T)

# Classification Uncertainty

In [17]:
''' This approach selects the 1 most uncertain sample. Large number represents uncertainty. We should pass multiple lists of probs
instead of 1 sample to get a list of uncertainities and select the one with highest number. In this case pass axis = 1 for max function '''

1 - class_probs.max(axis = 1) 

array([-0.5, -0.3, -0.3])

# Margin Sampling

In [18]:
''' Considers the margin between first and second most likely prediction. It selects the sample with smallest margin, the smaller the margin between the prediction of two classes the more unsure the decision is. '''

part = np.partition(-class_probs, 1, axis=1)
margin = - part[:, 0] + part[:, 1]
margin

array([0.3, 0. , 0.1])

# Images entropy and name sync check

In [30]:
import cv2
path = '/home/zain/Images/'
score = []
images = []
fileNames = []
for filename in os.listdir(path):
    img = cv2.imread(os.path.join(path, filename))
    images.append(img)
    fileNames.append(filename)

for image in images:  # calculate entropies for all images
    _, counts = np.unique(image, return_counts=True)
    score.append(entropy(counts))
chosenImages = sorted(zip(fileNames, score), key=lambda x: x[1])

print(chosenImages)

[('Lineitem_50gb_allcores.pdf', 0.0), ('Part_50gb_oldVSnew.pdf', 0.0), ('Lineitem_50gb_oldVSnew.pdf', 0.0), ('Part_1_50_100.pdf', 0.0), ('Part_50gb_allcores.pdf', 0.0), ('Lineitem_1_50_100.pdf', 0.0), ('elf-dimensions.png', 0.44059263518325487), ('pseudo code 2.png', 0.4576443437915783), ('code1.png', 0.49681698950052616), ('pseudo code 1.png', 0.5068818327734135), ('pseudo code 3.png', 0.5205344083450851), ('Elf with prefix redundancy (2).png', 0.5404919977770382), ('elf-table.png', 0.5443237373572787), ('code3.png', 0.5518325476432911), ('code2.png', 0.5645080632103111), ('MonoLists.png', 0.6198982202721546), ('Hashmap.png', 0.6514217065891794), ('Concept.png', 0.8310668220601269), ('Linearized Elf.png', 0.8768132404410574), ('prefixsum.png', 1.020057607605695), ('prev_code.png', 1.712885472348902)]


In [33]:
img = cv2.imread('/home/zain/Images/prefixsum.png')
_, counts = np.unique(img,return_counts=True)
print(entropy(counts))

1.020057607605695


In [34]:
cv2.__version__

'4.2.0'

In [35]:
path = '/home/zain/seafile-client/seafile/Zain/Images'
newPath = '/home/zain/seafile-client/seafile/Zain/newImages'
score = []
images = []
fileNames = []
for filename in os.listdir(path):
    img = cv2.imread(os.path.join(path, filename))
    images.append(img)
    fileNames.append(filename)

for image in images:  # calculate entropies for all images
    _, counts = np.unique(image, return_counts=True)
    score.append(entropy(counts))
chosenImages = sorted(zip(fileNames, score), key=lambda x: x[1])

print(chosenImages)